### ISSUE TITLE
Navigate Corporate Gift Cards Page

### ISSUE THREAD

**Issue by himanshuraj-glitches** [himanshuraj-glitches/MakeMyTrip#5]
This test case is failing always !!
Check the logic implementations and locators of the above-said test case
and also check whether all steps are written or not.

**Comment by singhpushkar001** [comment]
Ok i am trying to rectify this issue.

**Comment by himanshuraj-glitches** [comment]
Not fixed yet !!

**Comment by singhpushkar001** [comment]
Half of the portion is completed . I am working upon to rectify the issues . Will sort out shortly. Thanks
